.build_template: &build_template
  tags:
    - mylongtag
  script:
    - cd ${APP_DIR}
    - echo ${APP_DIR}
    - cmake . -DJOB_ID=$CI_JOB_ID
    - make
    - cd ..
    - echo ${APP_DIR}
  artifacts:
    paths:
      - ${APP_DIR}/bin/

build_hello_world_1:
  <<: *build_template
  variables:
    APP_DIR: "hello_world_1"

build_hello_world_2:
  <<: *build_template
  variables:
    APP_DIR: "hello_world_2"
  artifacts:
    paths:
      - $APP_DIR/bin/
      
build_hello_world_3:
  <<: *build_template
  variables:
    APP_DIR: "hello_world_3"
