
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/cmake/1366/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:7 (project)"
    message: |
      The system is: Linux - 5.4.0-150-generic - x86_64
