#!/usr/bin/python

import threading
import serial
import sys
import time
import re
import datetime
import os

list_TC = { 1:'SATA-Normal 2.1.1-CHECK_DMESG_AFTER_START_THE_BOARD', \
            2:'SATA-Normal 2.1.2-CHECK_INTERRUPT_AFTER_START_THE_BOARD', \
            3:'SATA-Normal 2.1.3-CHECK_HARD_DISK_SPEED_SATA', \
            4:'SATA-Normal 2.1.4-CHECK_HARD_DISK_CACHE_SATA', \
            5:'SATA-Normal 2.1.5--ENABLE_COMMAND_SECTION_SATA', \
            6:'SATA-Normal 2.1.6-READ_SMART_SECTION_SATA', \
            7:'SATA-Normal 2.1.7-READ_SMART_SECTION_SATA_ERROR',\
            8:'SATA-Normal 2.1.8-CREATING_PARTITION_AND_MAKING_FILE_SYSTEM_FOR_SATA',\
            9:'SATA-Normal 2.1.9-CREATING_PARTITION_AND_MAKING_FILE_SYSTEM_FOR_SATA',\
            10:'SATA-Normal 2.1.10-WRITE_DATA_FROM_RAM_TO_SATA_10MB_NO_DATA',\
            11:'SATA-Normal 2.1.11-WRITE_DATA_FROM_RAM_TO_SATA_100MB_NO_DATA',\
            12:'SATA-Normal 2.1.12-WRITE_DATA_FROM_RAM_TO_SATA_350MB_NO_DATA',\
            13:'SATA-Normal 2.1.13-WRITE_DATA_FROM_RAM_TO_SATA_ONE_FOLDER_NO_DATA',\
            14:'SATA-Normal 1.1.14-WRITE_DATA_FROM_RAM_TO_SATA_FIVE_FOLDERS_NO_DATA',\
            15:'SATA-Normal 2.1.15-WRITE_DATA_FROM_RAM_TO_SATA_10MB_HAS_DATA',\
            16:'SATA-Normal 2.1.16-WRITE_DATA_FROM_RAM_TO_SATA_100MB_HAS_DATA',\
            17:'SATA-Normal 2.1.17-WRITE_DATA_FROM_RAM_TO_SATA_350MB_HAS_DATA',\
            18:'SATA-Normal 2.1.18-WRITE_DATA_FROM_RAM_TO_SATA_ONE_FOLDER_HAS_DATA',\
            19:'SATA-Normal 2.1.19-WRITE_DATA_FROM_RAM_TO_SATA_FIVE_FOLERS_HAS_DATA',\
            20:'SATA-Normal 2.1.20-EXCEEDS_CAPACITY_WRITE',\
            21:'SATA-Normal 2.1.21-READ_DATA_FROM_SATA_TO_RAM_10MB',\
            22:'SATA-Normal 2.1.22-READ_DATA_FROM_SATA_TO_RAM_100MB',\
            23:'SATA-Normal 2.1.23-READ_DATA_FROM_SATA_TO_RAM_350MB',\
            24:'SATA-Normal 2.1.24-READ_DATA_FROM_SATA_TO_RAM_ONE_FOLDER',\
            25:'SATA-Normal 2.1.25-READ_DATA-FROM_SATA_TO_RAM_FIVE_FOLDERS',\
            26:'SATA-Normal 2.1.26-SIMULTANEOUSLY_COPY_RAM_AND_SATA_100MB',\
            27:'SATA-Normal 2.1.27-SIMULTANEOUSLY_COPY_RAM_AND_SATA_200MB',\
            28:'SATA-Normal 2.1.28-SIMULTANEOUSLY_COPY_INNER_100MB',\
            29:'SATA-Normal 2.1.29-SIMULTANEOUSLY_COPY_INNER_200MB',\
            30:'SATA-Normal 2.1.30-WRITE_SPEED_SATA_TEST',\
            31:'SATA-Normal 2.1.31-READ_SPEED_SATA_TEST',\
            32:'SATA-Normal 2.1.32-CHECK_INTERRUPT_COUTER_TIMER_TEST',\
            33:'SATA-Normal 2.1.33-SATA_UNBIND_BIND_DEVICE_TEST',\
            34:'SATA-Normal 2.1.34-SATA_UNBIND_BIND_DEVICE_WHILE_COPY',\
            35:'SATA-Normal 2.1.35-S2RAM_BEFORE_WRITING_DATA',\
            36:'SATA-Normal 2.1.36-S2RAM_BEFORE_READING_DATA',\
            37:'SATA-Normal 2.1.37-S2RAM_WHILE_WRITING_DATA',\
            38:'SATA-Normal 2.1.38-S2RAM_WHILE_READING_DATA',\
            #39:'SATA-Abnormal 2.1.39-SATA_PULL_OUT_DEVICE_WHILE_COPYING',\
            #40:'SATA-Abnormal 2.1.40-SATA_PULL OUT_DEVICE_WHILE_COPYING',\
            41:'SATA-Abnormal 2.1.41-CTR+C_WRITE_DATA',\
            42:'SATA-Abnormal 2.1.42-CTR+Z_WRITE_DATA',\
            43:'SATA-Boundary 2.1.43-SATA_TEST_BLOCK_OVER_SEEK',\
            44:'SATA-Boundary 2.1.44-SATA_TEST_BLOCK_OK',\
            45:'SATA-Boundary 2.1.45-SATA_TEST_FINAL_BLOCK_BY_LAST_BLOCK',\
            46:'SATA-Boundary 2.1.46-SATA_TEST_BLOCK_OVER_COUNT',\
            47:'SATA-SMP 2.1.47-SMP_TEST_MULTIPLE_CPU',\
            48:'SATA-Durability 2.1.48-SATA_TEST_WRITE_DATA_100_TIMES',\
            49:'SATA-Durability 2.1.49-SATA_TEST_READ_DATA_100_TIMES'         
} 
