#!/usr/bin/python

import threading
import serial
import sys
import time
import re
import datetime
import os

list_TC = { 1:'DMAE-Normal 2.1.1-CHECK_DMESG_AFTER_START_THE_BOARD', \
            2:'DMAE-Normal 2.1.2-DMAE_CHECK_DEVICE_TEST', \
            3:'DMAE-Normal 2.1.3-DMAE_CHECK_DMA_CHAN_TEST_AUDIO_DMAC0', \
            4:'DMAE-Normal 2.1.4-DMAE_CHECK_DMA_CHAN_TEST_AUDIO_DMAC1', \
            5:'DMAE-Normal 2.1.5-DMAE_CHECK_DMA_CHAN_TEST_SYS_DMAC0', \
            6:'DMAE-Normal 2.1.6-DMAE_CHECK_DMA_CHAN_TEST_SYS_DMAC1', \
            7:'DMAE-Normal 2.1.7-DMAE_CHECK_DMA_CHAN_TEST_SYS_DMAC2',\
            8:'DMAE-Normal 2.1.8-DMAE_CHECK_DMA_CHAN_TEST_USB_DMAC0',\
            9:'DMAE-Normal 2.1.9-DMAE_CHECK_DMA_CHAN_TEST_USB_DMAC1',\
            10:'DMAE-Normal 2.1.10-CHECK_INTERRUPT_SYS_DMAC0_AFTER_STARTING_THE_BOARD',\
            11:'DMAE-Normal 2.1.11-CHECK_INTERRUPT_SYS_DMAC1_AFTER_STARTING_THE_BOARD',\
            12:'DMAE-Normal 2.1.12-CHECK_INTERRUPT_SYS_DMAC2_AFTER_STARTING_THE_BOARD',\
            13:'DMAE-Normal 2.1.13-CHECK_INTERRUPT_AUDIO_DMAC0_AFTER_STARTING_THE_BOARD',\
            14:'DMAE-Normal 2.1.14-CHECK_INTERRUPT_AUDIO_DMAC1_AFTER_STARTING_THE_BOARD',\
            15:'DMAE-Normal 2.1.15-CHECK_INTERRUPT_USB_DMAC0_AFTER_STARTING_THE_BOARD',\
            16:'DMAE-Normal 2.1.16-CHECK_INTERRUPT_USB_DMAC1_AFTER_STARTING_THE_BOARD',\
            17:'DMAE-Normal 2.1.17-MEMCOPY_DATA_TRANFERS_TEST_SYS_DMAC0',\
            18:'DMAE-Normal 2.1.18-MEMCOPY_DATA_TRANFERS_TEST_SYS_DMAC1',\
            19:'DMAE-Normal 2.1.19-MEMCOPY_DATA_TRANFERS_TEST_SYS_DMAC2',\
            20:'DMAE-Normal 2.1.20-MEMCOPY_DATA_TRANFERS_TEST_AUDIO_DMAC0',\
            21:'DMAE-Normal 2.1.21-MEMCOPY_DATA_TRANFERS_TEST_ADUIO_DMAC1',\
            24:'DMAE-Normal 2.1.24-DMAE_UNBIND_BIND_DEVICE_TEST_SYS_DMAC0',\
            26:'DMAE-Normal 2.1.26-DMAE_UNBIND_BIND_DEVICE_TEST_SYS_DMAC2',\
            27:'DMAE-Normal 2.1.27-DMAE_UNBIND_BIND_DEVICE_TEST_AUDIO_DMAC0',\
            28:'DMAE-Normal 2.1.28-DMAE_UNBIND_BIND_DEVICE_TEST_AUDIO_DMAC1',\
            29:'DMAE-Normal 2.1.29-DMAE_UNBIND_BIND_DEVICE_TEST_USB_DMAC0',\
            30:'DMAE-Normal 2.1.30-DMAE_UNBIND_BIND_DEVICE_TEST_USB_DMAC1',\
            31:'DMAE-Normal 2.1.31-DMAE_S2RAM_WHEN_PLAYING_AUDIO',\
            32:'DMAE-Normal 2.1.32-DMAE_S2RAM_WHEN_RECORDING',\
            33:'DMAE-Normal 2.1.33-DMAE_DMATEST_MEMCPY_SYS_DMAC_AUDIO_DMAC'\
} 
