include:
  - build.yml
  - test.yml

# stages:
#   - build
#   - test

# .build_template:
#   stage: build

#   script:
#     - cd ${APP_DIR}
#     - mkdir build && cd build
#     - cmake -DJOB_ID=${JOB_ID} ..
#     - make
#     - cd .. && ls
#   artifacts:
#     paths:
#       - ${APP_DIR}/build/


# build_hello_world_1:
#   extends: 
#     - .build_template
#   variables:
#     APP_DIR: "hello_world_1"
#     JOB_ID: "1"

# build_hello_world_2:
#   extends: 
#     - .build_template
#   variables:
#     APP_DIR: "hello_world_2"
#     JOB_ID: "2"

# build_hello_world_3:
#   extends: 
#     - .build_template
#   variables:
#     APP_DIR: "hello_world_3"
#     JOB_ID: "3"

# .test_template:
#   stage: test

#   script:
#     - ls
#     - cd ${APP_DIR}/build/bin/
#     - ./${APP_DIR}

# test_hello_world_1:
#   extends: 
#     - .test_template
#   variables:
#     APP_DIR: "hello_world_1"
#     JOB_ID: "1"
#   stage: test
#   dependencies:
#     - build_hello_world_1

# test_hello_world_2:
#   extends: 
#     - .test_template
#   variables:
#     APP_DIR: "hello_world_2"
#     JOB_ID: "2"
#   stage: test
#   dependencies:
#     - build_hello_world_2

# test_hello_world_3:
#   extends: 
#     - .test_template
#   variables:
#     APP_DIR: "hello_world_3"
#     JOB_ID: "3"
#   stage: test
#   dependencies:
#     - build_hello_world_3 

# stages:
#   - build
#   - test

# build:
#   stage: build
#   script:
#     - mkdir build
#     - cd build
#     - cmake .. -DJOB_ID=$CI_JOB_ID
#     - make
#   artifacts:
#     paths:
#       - build/
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "push"'
#       when: never
#     - when: always

# test:
#   stage: test
#   script:
#     - /home/tri.tran-minh2/builds/3vp5BZnF/0/tri.tran-minh2/cicd/build/bin/hello_world_1
#     - /home/tri.tran-minh2/builds/3vp5BZnF/0/tri.tran-minh2/cicd/build/bin/hello_world_2
#     - /home/tri.tran-minh2/builds/3vp5BZnF/0/tri.tran-minh2/cicd/build/bin/hello_world_3
#   dependencies:
#     - build
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "push"'
#       when: never
#     - when: always

