#!/usr/bin/python

import threading
import serial
import sys
import time
import re
import datetime
import os

list_TC = { 1:'USB2F-Normal 2.1.1-CHECK_DMESG_AFTER_START_THE_BOARD', \
            2:'USB2F-Normal 2.1.2-CHECK_INTERRUPT_AFTER_START_THE_BOARD', \
            3:'USB2F-Normal 2.1.3-USBFS_SERIAL_SETTING', \
            4:'USB2F-Normal 2.1.4-USBFS_SERIAL_BOARD_TO_PC', \
            5:'USB2F-Normal 2.1.5-USBFS_SERIAL_PC_TO_BOARD',\
            6:'USB2F-Normal 2.1.6-USBFS_SERIAL_S2RAM', \
            7:'USB2F-Normal 2.1.7-USBFS_ETHERNET_SETTING',\
            8:'USB2F-Normal 2.1.8-USBFS_ETHERNET_PING_BOARD_TO_PC',\
            9:'USB2F-Normal 2.1.9-USBFS_ETHERNET_PING_PC_TO_BOARD',\
            10:'USB2F-Normal 2.1.10-USBFS_ETHERNET_S2RAM',\
            11:'USB2F-Normal 2.1.11-USBFS_STORAGE_SETTING',\
            12:'USB2F-Normal 2.1.12-USBFS_STORAGE_RAM_PC_TO_BOARD_10M',\
            13:'USB2F-Normal 2.1.13-USBFS_STORAGE_RAM_PC_TO_BOARD_100M',\
            14:'USB2F-Normal 2.1.14-USBFS_STORAGE_RAM_PC_TO_BOARD_300M',\
            15:'USB2F-Normal 2.1.15-USBFS_STORAGE_RAM_BOARD_TO_PC_10M',\
            16:'USB2F-Normal 2.1.16-USBFS_STORAGE_RAM_BOARD_TO_PC_100M',\
            17:'USB2F-Normal 2.1.17-USBFS_STORAGE_RAM_BOARD_TO_PC_300M',\
            18:'USB2F-Normal 2.1.18-USBFS_STORAGE_RAM_WRITING_SPEED_TEST',\
            19:'USB2F-Normal 2.1.19-USBFS_STORAGE_RAM_READING_SPEED_TEST',\
            20:'USB2F-Normal 2.1.20-USBFS_STORAGE_RAM_NO_SPACE_LEFT',\
            21:'USB2F-Normal 2.1.21-USBFS_STORAGE_RAM_S2RAM',\
            30:'USB2F-Normal 2.1.30-USBFS_AUDIO_RECORDING',\
            31:'USB2F-Normal 2.1.31-USBFS_AUDIO_PLAYBACK',\
            34:'USB2F-Normal 2.1.34-USBFS_G_ZERO_CONTROL_TRANSFER_WRITING_HIGH_SPEED',\
            35:'USB2F-Normal 2.1.35-USBFS_G_ZERO_CONTROL_TRANSFER_READING_HIGH_SPEED',\
            36:'USB2F-Normal 2.1.36-USBFS_G_ZERO_BULK_TRANSFER_READING_HIGH_SPEED',\
            37:'USB2F-Normal 2.1.37-USBFS_G_ZERO_BULK_TRANSFER_READING_HIGH_SPEED',\
            44:'USB2F-Normal 2.1.44-USBFS_SERIAL_PULL_OUT_WHILE_TRANSFERING',\
            45:'USB2F-Normal 2.1.45-USBFS_ETHERNET_PULL_OUT_WHILE_TRANSFERING',\
            46:'USB2F-Normal 2.1.46-USBFS_STORAGE_PULL_OUT_WHILE_TRANSFERING',\
            47:'USB2F-Normal 2.1.47-USBFS_ETHERNET_SMP',\
            48:'USB2F-Normal 2.1.48-USBFS_STORAGE_RAM_STRESS_TEST',\
}

#back up
#            22:'USB2F-Normal 2.1.22-USBFS_STORAGE_SD_PC_TO_BOARD_100M',\
#            23:'USB2F-Normal 2.1.23-USBFS_STORAGE_SD_PC_TO_BOARD_500M',\
#            24:'USB2F-Normal 2.1.24-USBFS_STORAGE_SD_PC_TO_BOARD_1G',\
#            25:'USB2F-Normal 2.1.25-USBFS_STORAGE_SD_BOARD_TO_PC_100M',\
#            26:'USB2F-Normal 2.1.26-USBFS_STORAGE_SD_BOARD_TO_PC_500M',\
#            27:'USB2F-Normal 2.1.27-USBFS_STORAGE_SD_BOARD_TO_PC_1G',\
#            28:'USB2F-Normal 2.1.28-USBFS_STORAGE_SD_WRITING_SPEED',\
#            29:'USB2F-Normal 2.1.29-USBFS_STORAGE_SD_READING_SPEED',\
 
