#!/usr/bin/python


list_TC = { 1:'PCIe-Normal 2.1.1-CHECK_DMESG_ACTIVATION_AFTER_START_THE_BOARD', \
            2:'PCIe-Normal 2.1.2-CHECK_DMESG_AFTER_START_THE_BOARD', \
            3:'PCIe-Normal 2.1.3-CHECK_DMESG_MAC_ADDRESS', \
            4:'PCIe-Normal 2.1.4-CHECK_ETHERNET_ACTIVATION_UP_DOWN', \
            5:'PCIe-Normal 2.1.5-SETTING_IP_ADDRESS', \
            6:'PCIe-Normal 2.1.6-SETTING_NET_MASK', \
            7:'PCIe-Normal 2.1.7-CHECK_DMESG_ETHTOOL',\
            8:'PCIe-Normal 2.1.8-CHECK_INTERRUPT',\
            9:'PCIe-Normal 2.1.9-PING_ECHO_PACKET_RECEPTION',\
            10:'PCIe-Normal 2.1.10-PING_ECHO_PACKET_TRANSMISSION',\
            11:'PCIe-Normal 2.1.11-CHECK_FTP_UPLOAD',\
            12:'PCIe-Normal 2.1.12-CHECK_FTP_DOWNLOAD',\
            13:'PCIe-Normal 2.1.13-CONFIRM_TRANSMISSION_ENABLED_FULL_DUPLEX_1000M',\
            14:'PCIe-Normal 2.1.14-CONFIRM_TRANSMISSION_ENABLED_FULL_DUPLEX_100M',\
            15:'PCIe-Normal 2.1.15-CONFIRM_TRANSMISSION_ENABLED_FULL_DUPLEX_10M',\
            #16:'PCIE-Normal 2.1.16-CONFIRM_TRANSMISSION_ENABLED_HALF_DUPLEX_1000M',\
            17:'PCIe-Normal 2.1.17-CONFIRM_TRANSMISSION_ENABLED_HALF_DUPLEX_100M',\
            18:'PCIe-Normal 2.1.18-CONFIRM_TRANSMISSION_ENABLED_HALF_DUPLEX_10M',\
            #19:'PCIE-Normal 2.1.19-CONFIRM_TRANSMISSION_DISABLED_FULL_DUPLEX_1000M',\
            20:'PCIe-Normal 2.1.20-CONFIRM_TRANSMISSION_DISABLED_FULL_DUPLEX_100M',\
            21:'PCIe-Normal 2.1.21-CONFIRM_TRANSMISSION_DISABLED_FULL_DUPLEX_10M',\
            22:'PCIe-Normal 2.1.22-CONFIRM_TRANSMISSION_DISABLED_HALF_DUPLEX_1000M',\
            23:'PCIe-Normal 2.1.23-CONFIRM_TRANSMISSION_DISABLED_HALF_DUPLEX_100M',\
            24:'PCIe-Normal 2.1.24-CONFIRM_TRANSMISSION_DISABLED_HALF_DUPLEX_10M',\
            25:'PCIe-Normal 2.1.25-IPERF_TRANFERS_RATE_FROM_BOARD_TO_HOST_PC',\
            26:'PCIe-Normal 2.1.26-IPERF_TRANFERS_RATE_FROM_HOST_PC_TO_BOARD',\
            27:'PCIe-Normal 2.1.27-CONFIRM_TRANSMISSION_SPEED_FULL_DUPLEX_10M',\
            28:'PCIe-Normal 2.1.28-CONFIRM_TRANSMISSION_SPEED_HALF_DUPLEX_10M',\
            29:'PCIe-Normal 2.1.29-CONFIRM_OPERATION_AFTER_S2RAM',\
            30:'PCIe-Normal 2.1.30-SUSPEND_SYSTEM_WHILE_TRANSMITTING_DATA',\
            31:'PCIe-Abnormal 2.1.31-EXTRACT_ETH_WHILE_SENDING_DATA_VIA_ETHERNET',\
            #32:'PCIE-Abnormal 2.1.32-PULL_OUT_CABLE_WHILE_TRANSMITTING_VIA_ETHERNET',\
            33:'PCIe-Abnormal-2.1.33-Ctr_C_DURING_TRANFER_DATA_FORM_BOARD_TO_HOST_PC',\
            34:'PCIe-Abnormal-2.1.34-Ctr_C_DURING_TRANFER_DATA_FROM_HOST_PC_TO_BOARD',\
            35:'PCIe-Abnormal-2.1.35-Ctr_Z_DURING_TRANFER_DATA_FORM_BOARD_TO_HOST_PC',\
            36:'PCIe-Abnormal-2.1.36-Ctr_Z_DURING_TRANFER_DATA_FROM_HOST_PC_TO_BOARD',\
            37:'PCIe-Boundary-2.1.37-Check_class_A_IP_ADDRESS',\
            38:'PCIe-Boundary-2.1.38-Check_class_B_IP_ADDRESS',\
            39:'PCIe-Boundary-2.1.39-Check_class_C_IP_ADDRESS',\
            40:'PCIe-Boundary-2.1.40-Check_class_D_IP_ADDRESS',\
            41:'PCIe-Boundary-2.1.41-Check_class_E_IP_ADDRESS',\
            42:'PCIe-SMP-2.1.42-SMP_CONCURRENT_ACCESS_TEST',\
            43:'PCIe-Durability-2.1.43-STRESS_CPU_TEST'\
} 
